####################
# USER API REQUEST #
####################

###
#GET http://localhost:8000/v1/users
GET http://localhost:8000/v1/users

###
#GET http://localhost:8000/v1/users/:userId
GET http://localhost:8000/v1/users/62c6697a4b8212e4674dbe14

###
#POST http://localhost:8000/v1/users/oauth
POST http://localhost:8000/v1/users/oauth
Content-Type: application/json

{
 "user_nickname": "보석깅깅깅", 
 "user_gender" : true,
  "user_weekday" : {
    "mon":  true
  }, 
  "user_schedule_time": 0, 
  "user_address" : "전라남도 광주광역시 광산구 송정동 상무대로 312", 
  "user_latitude" : 35.142905, 
  "user_longitude": 126.800562, 
  "fitness_center_name" : "하위 피트니스",



  "name": "김보석",
  "picture": "https://graph.facebook.com/1626030847797342/picture",
  "iss": "https://securetoken.google.com/fitmate-cf118",
  "aud": "fitmate-cf118",
  "auth_time": 1657436473,
  "user_id": "q6KlqMtj18NFpWHvOB2tQs24PvM2",
  "sub": "q6KlqMtj18NFpWHvOB2tQs24PvM2",
  "iat": 1657436473,
  "exp": 1657440073,
  "email": "boseoggim08@gmail.com",
  "email_verified": false,
  "firebase": {
    "identities": { "facebook.com": [], "email": [] },
    "sign_in_provider": "facebook.com"
  },
  "uid": "q6KlqMtj18NFpWHvOB2tQs24PvM2"
}

###

###
#POST http://localhost:8000/v1/users/info/
POST http://localhost:8000/v1/users/info/

###
#PATCH http://localhost:8000/v1/users/:userId
PATCH http://localhost:8000/v1/users/62c6697a4b8212e4674dbe14
Content-Type: application/json

{
    "user_name":"김규민 버전2",
    "user_weekday": { "sat":true},
    "user_profile_img": "https://i1.sndcdn.com/artworks-000280219757-ls2h99-t500x500.jpg"
}