####################
# USER API REQUEST #
####################



###
GET http://localhost:8000/api-docs


###
#GET http://localhost:8000/v1/users/login
GET http://localhost:8000/v1/users/login
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6ImJmMWMyNzQzYTJhZmY3YmZmZDBmODRhODY0ZTljMjc4ZjMxYmM2NTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZml0bWF0ZS1jZjExOCIsImF1ZCI6ImZpdG1hdGUtY2YxMTgiLCJhdXRoX3RpbWUiOjE2NTgyODk1NjAsInVzZXJfaWQiOiI3dXFRaThVWW1QTTl1Z2tkbm9xVjExeEJhUE8yIiwic3ViIjoiN3VxUWk4VVltUE05dWdrZG5vcVYxMXhCYVBPMiIsImlhdCI6MTY1ODI4OTU2MCwiZXhwIjoxNjU4MjkzMTYwLCJlbWFpbCI6InRlc3RAaGkuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3RAaGkuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.Fwz5GxxXIZ_lRnTa00V0-NnlXgsd5DboP-j2tCCGfTZ9HGXgJ3oPmYjqRgMfTQtUmqEHY6nu2W1ucXzLGxfIctrbuHsSSw777Z1mbCMIYk1AkB7I__BtC3r53nW-hS3wL7BmKWZHEawhY4px3MYqdU1jPNHeQJ2WN6etgO0KeXmPoVMiQk6OQ905LiR68IbnWOVpp57YJ28qKqYWRH-BYPvaAnZe5B_31GwMjMubkxuJrHRQY9gVyRFrzfU0XPrlvlyGes7UDCjwXpCa5it_ET2XCYVb5nttKCPQ9CVuzOom2_A6k9etiEtgMxY4wMCGQg-M3EiJSSkVccPOnfduTQ



###
#GET http://localhost:8000/v1/users
GET http://localhost:8000/v1/users
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6ImVhNWY2NDYxMjA4Y2ZmMGVlYzgwZDFkYmI1MjgyZTkyMDY0MjAyNWEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZml0bWF0ZS1jZjExOCIsImF1ZCI6ImZpdG1hdGUtY2YxMTgiLCJhdXRoX3RpbWUiOjE2NTgyMzMwMjksInVzZXJfaWQiOiI3dXFRaThVWW1QTTl1Z2tkbm9xVjExeEJhUE8yIiwic3ViIjoiN3VxUWk4VVltUE05dWdrZG5vcVYxMXhCYVBPMiIsImlhdCI6MTY1ODIzMzAyOSwiZXhwIjoxNjU4MjM2NjI5LCJlbWFpbCI6InRlc3RAaGkuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3RAaGkuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.tmtZDGazgSR3ChyGZCJNKuolZaSFdabIw3dMGuRzXDixWJFJVivfXpPIHaTWNQuATL2P1jKvazlSRrSIZulG_nWzP8db9HsYOlpowae-NKyyk9HoNGW4W-IZec5s4OUypoEzmv0BheXiAhBlNJ521i6mr5kiwyr-DD6jlMvdgxFhhRa9VyynfdFJdWUbFA_fEE47LUtkGSPakr4qcbufZoL_Ifjg2VzA5-lRn-Hx3rM1st3xIa8rn-eGiptkB_IbEy98lao1rAcNW4J1YqJP1ZM-RDe_oa-eMefapyC2ehJYIVxnQ9c0fnuMFT4HZj6zERYgOWnIo-1-CmX9jjrfyw




###
#GET http://localhost:8000/v1/users/:userId
GET http://localhost:8000/v1/users/62c6697a4b8212e4674db
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6ImJmMWMyNzQzYTJhZmY3YmZmZDBmODRhODY0ZTljMjc4ZjMxYmM2NTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZml0bWF0ZS1jZjExOCIsImF1ZCI6ImZpdG1hdGUtY2YxMTgiLCJhdXRoX3RpbWUiOjE2NTgyODk1NjAsInVzZXJfaWQiOiI3dXFRaThVWW1QTTl1Z2tkbm9xVjExeEJhUE8yIiwic3ViIjoiN3VxUWk4VVltUE05dWdrZG5vcVYxMXhCYVBPMiIsImlhdCI6MTY1ODI4OTU2MCwiZXhwIjoxNjU4MjkzMTYwLCJlbWFpbCI6InRlc3RAaGkuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3RAaGkuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.Fwz5GxxXIZ_lRnTa00V0-NnlXgsd5DboP-j2tCCGfTZ9HGXgJ3oPmYjqRgMfTQtUmqEHY6nu2W1ucXzLGxfIctrbuHsSSw777Z1mbCMIYk1AkB7I__BtC3r53nW-hS3wL7BmKWZHEawhY4px3MYqdU1jPNHeQJ2WN6etgO0KeXmPoVMiQk6OQ905LiR68IbnWOVpp57YJ28qKqYWRH-BYPvaAnZe5B_31GwMjMubkxuJrHRQY9gVyRFrzfU0XPrlvlyGes7UDCjwXpCa5it_ET2XCYVb5nttKCPQ9CVuzOom2_A6k9etiEtgMxY4wMCGQg-M3EiJSSkVccPOnfduTQ





###
#POST http://localhost:8000/v1/users/oauth
POST http://localhost:8000/v1/users/oauth
Content-Type: application/json
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6ImVhNWY2NDYxMjA4Y2ZmMGVlYzgwZDFkYmI1MjgyZTkyMDY0MjAyNWEiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZml0bWF0ZS1jZjExOCIsImF1ZCI6ImZpdG1hdGUtY2YxMTgiLCJhdXRoX3RpbWUiOjE2NTgyMzA3NzEsInVzZXJfaWQiOiI3dXFRaThVWW1QTTl1Z2tkbm9xVjExeEJhUE8yIiwic3ViIjoiN3VxUWk4VVltUE05dWdrZG5vcVYxMXhCYVBPMiIsImlhdCI6MTY1ODIzMDc3MSwiZXhwIjoxNjU4MjM0MzcxLCJlbWFpbCI6InRlc3RAaGkuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3RAaGkuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.L-bXxtDTJzqCmGh5epoaHDzQaX5blU_xY_pIvs1sBQnEoEjtDad17DJZuBrAuc0GfDazWM8C4DeyFK2VmWkkdjApjebDWRFPJd9f1AiINEiIV8E2LBsvSyJDhJVQ-P_DWVzQplxEowFMX_ES5TGBwl8D1zMiqilMlVwkLWBWSn9d30O-hEee__5nrXaMOAeFFHSvSVr8foCMfRxs9QYMyRAy8m_JTNU-majBJedWfaMPraa5zRSveKcl_5YfvOOwUQJrCzU2Af2hyfeuktfskYCgiqggGI6BQBxYGJkG2a7341ACvBzsRxdOn90RKAxEU3ZxZGGGtJ2KFScxU7dtSA


{
 "user_nickname": "testHii", 
 "user_gender" : true, 
  "user_schedule_time": 0, 
  "user_address" : "서울특별시 강남구 송정동 상무대로 312", 
  "user_latitude" : 35.142905, 
  "fitness_center" : {
      "center_name":"무야호짐",
      "center_address":"서울시 강남구 구의로 579 B104호",
		  "center_latitude": 123.5,
		  "center_longitude": 123.2334
  }
}




###
#POST http://localhost:8000/v1/users/oauth
POST http://localhost:8000/v1/users/oauth
Content-Type: application/json
user_id : 62c6697a4b8212e4674dbe14

{
 "user_nickname": "규민민", 
 "user_gender" : true,
  "user_weekday" : {
    "fri":  true
  }, 
  "user_schedule_time": 0, 
  "user_address" : "서울특별시 강남구 송정동 상무대로 312", 
  "user_latitude" : 35.142905, 
  "user_longitude": 126.800562, 
  "fitness_center" : {
      "center_name":"무야호짐",
      "center_address":"서울시 강남구 구의로 579 B104호",
		  "center_latitude": 123.5,
		  "center_longitude": 123.2334
  },



  "name": "김규민",
  "picture": "https://graph.facebook.com/1626030847797342/picture",
  "iss": "https://securetoken.google.com/fitmate-cf118",
  "aud": "fitmate-cf118",
  "auth_time": 1657436473,
  "user_id": "q6KlqMtj18NFpWHvOB2tQs24PvM2",
  "sub": "q6KlqMtj18NFpWHvOB2tQs24PvM2",
  "iat": 1657436473,
  "exp": 1657440073,
  "email": "hihi@gmail.com",
  "email_verified": false,
  "firebase": {
    "identities": { "facebook.com": [], "email": [] },
    "sign_in_provider": "facebook.com"
  },
  "uid": "q6KlqMtj18NFpWHvOB2tQs24PvM2"
}



###
#POST http://localhost:8000/v1/users/info/
POST http://localhost:8000/v1/users/info/

###
#PATCH http://localhost:8000/v1/users/:userId
PATCH http://localhost:8000/v1/users/62c6697a4b8212e4674dbe14
Content-Type: application/json

{
    "user_name":"김규민 버전2",
    "user_weekday": { "sat":true},
    "user_profile_img": "https://i1.sndcdn.com/artworks-000280219757-ls2h99-t500x500.jpg"
}



###





####################
# POST API REQUEST #
####################

#GET http://localhost:8000/v1/posts/
GET http://localhost:8000/v1/posts/
Authorization: eyJhbGciOiJSUzI1NiIsImtpZCI6ImJmMWMyNzQzYTJhZmY3YmZmZDBmODRhODY0ZTljMjc4ZjMxYmM2NTQiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vZml0bWF0ZS1jZjExOCIsImF1ZCI6ImZpdG1hdGUtY2YxMTgiLCJhdXRoX3RpbWUiOjE2NTgyOTIyNzgsInVzZXJfaWQiOiI3dXFRaThVWW1QTTl1Z2tkbm9xVjExeEJhUE8yIiwic3ViIjoiN3VxUWk4VVltUE05dWdrZG5vcVYxMXhCYVBPMiIsImlhdCI6MTY1ODI5MjI3OCwiZXhwIjoxNjU4Mjk1ODc4LCJlbWFpbCI6InRlc3RAaGkuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7ImVtYWlsIjpbInRlc3RAaGkuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.T2krK4Dj_fy95BKZiAFOW2DLpz6_d9nwYueTsHkaY5Cs8H2CUbsQXMzbtg0F0cDMVSCMCuU-OAowwD3I5RE2WorSzK934X39OuCFXmXlS5Lmdhg05lPTisu-5Y1ScCm2DCNUHgV1HcwPMlYP3_v2dLj9J1kVdjIOXJjP7QVXQWPvsP14pblJHMyPRrcbSb9wr5R5105gstKYtT9W-ktz9wO0kdlP0Ktubi5TttB4b2nJaCVEWQ-6B_7RIFRyS1UFqGoD4NfaCz3s5cGx-2A2UfernzSgjs9mdWOw7RX2Yag5BCl9p3Ezd2WKzxIp4zSYuVUCxrBfMEhttSUQRweIRg

###
#GET http://localhost:8000/v1/posts/:postId
GET http://localhost:8000/v1/posts/62c91f374b3a0eaed88e7a7d

###
#POST http://localhost:8000/v1/posts/
POST http://localhost:8000/v1/posts/
Content-Type: application/json

{
  "user_id": "62c66d3d4b8212e4674dbe18",
  "location_id": "62c66fbf4b8212e4674dbe2a",
  "post_fitness_part":["62c670514b8212e4674dbe34", "62c6705e4b8212e4674dbe35"],
  "post_title":"내일 여의도역 19시 스타트원짐 같이 등 가슴해요!",
  "promise_location": "62c672034b8212e4674dbe4b",
  "promise_date": "2022-07-12T19:00:00.000+00:00",
  "post_img": "https://www.korea.kr/newsWeb/resources/attaches/2016.11/08/2735a156cafd3ec8c1300e08fed9cf09.jpg",
  "post_main_text": "안녕하세요 여의도 2년차 직딩이에요!\n요즘 운동을 너무 쉬었더니 살이 너무 쪘네요ㅠㅠ\n근처 계시는 분들, 같이 운동하고 살빼요!!"
}


###
#PATCH http://localhost:8000/v1/posts/:postId
PATCH http://localhost:8000/v1/posts/62cbb42936bf379224d1edd9
Content-Type: application/json

{
    "post_title":"STARTONE GYM WORKOUT 기릿ㄱㄱ",
  "post_fitness_part":["62c670664b8212e4674dbe36"],
    "promise_date": "2022-07-12T10:00:00.000+00:00",
      "post_main_text": "뒤룩뒤룩 여의도에는 돼지가 살아요~~\n\n근처에 계시는 분들, 같이 운동하고 살빼요!!"
}


###
#DELETE http://localhost:8000/v1/posts/:postId
DELETE http://localhost:8000/v1/posts/62cbb7a4e03e3b9ad962e408



#####################
# Match API REQUEST #
#####################


###
#POST http://localhost:8000/v1/matching/:appointmentId
POST http://localhost:8000/v1/matching/62cb03648cf57fb306c82f6d
Content-Type: application/json

{
	"user_1": {
	    "userId": "62c66c2c4b8212e4674dbe17",
		"user_latitude": 37.50228,
		"user_longitude": 127.053906
	},
    "user_2":{
		"userId": "62c66aef4b8212e4674dbe16",
		"user_latitude": 37.502367,
		"user_longitude": 127.053864
    }
}



####

GET http://localhost:8000/qwe
Content-Type: application/json

{
  "fitness_center":{
		    "center_name":"아크로00000",
		    "center_address":"서울시 광진구 구의로 579 B104호",
		    "center_latitude": "233.5",
		    "center_longitude": "233.5"
			}
}


###

