

POST http://localhost:8000/trace
Content-Type: application/json

{
    "user_id" : "62c66c2c4b8212e4674dbe17",
    "user_longitude" : 9999.90,
    "user_latitude" :  1111.11
}

###
POST http://localhost:8000/trace1
Content-Type: application/json

{
    "user_id" : "62c66c2c4b8212e4674dbe17",
    "user_longitude" : 7777.90,
    "user_latitude" :  5555.11
}
###
GET http://localhost:8000/app

###

POST http://localhost:8000/app
